# Generated by Django 5.2.8 on 2025-11-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0003_notice_category"),
        ("notices", "0006_attachment_file_type_original_name"),
    ]

    operations = []
