# Generated by Django 5.2.8 on 2025-11-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0007_merge_20251117_1322"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notice",
            new_name="notices_not_categor_30f710_idx",
            old_name="notices_not_category_idx",
        ),
    ]
