# Generated by Django 4.2.11 on 2025-11-19 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notices', '0008_rename_notices_not_category_idx_notices_not_categor_30f710_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_at', models.DateTimeField()),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['remind_at'],
            },
        ),
        migrations.CreateModel(
            name='NoticeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title_template', models.CharField(blank=True, max_length=200)),
                ('description_template', models.TextField()),
                ('category', models.CharField(choices=[('campus_life', 'Campus Life'), ('business', 'Business'), ('education', 'Education'), ('general', 'General')], default='general', max_length=32)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('important', 'Important'), ('normal', 'Normal')], default='normal', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notice',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('important', 'Important'), ('normal', 'Normal')], default='normal', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['priority'], name='notices_not_priorit_da59d7_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['expires_at'], name='notices_not_expires_179ee9_idx'),
        ),
        migrations.AddField(
            model_name='noticetemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticereminder',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='notices.notice'),
        ),
        migrations.AddField(
            model_name='noticereminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='noticereminder',
            unique_together={('notice', 'user', 'remind_at')},
        ),
    ]
